import { getGroqClient } from "./client";
import { extractJson } from "./extract-json";
import {
	APPROX_WEIGHT_RULE,
	BASENAME_RULE,
	CATEGORY_RULE,
	GROCERY_CATEGORY_ENUM_LIST,
} from "./prompt-rules";
import {
	type CategorizeIngredientsResponse,
	categorizeIngredientsResponseSchema,
} from "./schema";

// Reuses the recipe-generation model rather than the cheap on-topic-check
// one — this pass has to correctly apply the same nuanced baseName rule a
// fresh generation does (see prompt-rules.ts), and a wrong correction here
// would misfile an ingredient for good (or wrongly merge/split it on the
// grocery list), so it's worth the extra cost for a one-time cleanup.
const CATEGORIZE_MODEL = "openai/gpt-oss-120b";

// One batch's worth of items comfortably fits well under this — sized the
// same way as the recipe continuation call (a similarly-sized array of
// small objects), not the full recipe-generation budget.
const CATEGORIZE_MAX_COMPLETION_TOKENS = 4096;

const CATEGORIZE_INGREDIENTS_SYSTEM_PROMPT = `You clean up a batch of already-generated grocery ingredient entries from a recipe app. You'll receive a JSON array of items, each with an "id", "baseName", and "description" exactly as generated by an earlier pass that didn't yet enforce today's rules. For each item, in order:

1. Check whether baseName/description already follow the rule below. If they already do, return them completely unchanged (byte-for-byte — do not rephrase for style, casing, or wording alone). If baseName violates it — e.g. it bakes in a preparation method that belongs in description, or lumps together what should be separate baseNames (different cuts/forms/products), or uses the wrong plurality — correct baseName and move any misplaced detail into description.
2. Assign a "category" from the fixed list in the rule below.
3. Give an "approxGramsPerUnit" per the rule below — this is a property of the ingredient itself (how much one whole piece weighs), independent of which unit any particular recipe happened to use it with.

${BASENAME_RULE}

${CATEGORY_RULE}

${APPROX_WEIGHT_RULE}

Respond with ONLY a JSON object (no other text) of the exact shape:
{ "items": [ { "id": number (echo the input item's id exactly, unchanged), "baseName": string, "description": string, "category": ${GROCERY_CATEGORY_ENUM_LIST}, "approxGramsPerUnit": number | null } ] }

Return exactly one output item per input item — never merge, split, drop, or add items — matched back by id, in any order.`;

export type CategorizeIngredientsInput = {
	id: number;
	baseName: string;
	description: string;
};

export type CategorizeIngredientsResult =
	| { type: "error"; message: string }
	| { type: "success"; items: CategorizeIngredientsResponse["items"] };

export async function categorizeIngredients(
	items: CategorizeIngredientsInput[],
): Promise<CategorizeIngredientsResult> {
	const client = getGroqClient();

	try {
		const completion = await client.chat.completions.create({
			model: CATEGORIZE_MODEL,
			response_format: { type: "json_object" },
			max_completion_tokens: CATEGORIZE_MAX_COMPLETION_TOKENS,
			messages: [
				{ role: "system", content: CATEGORIZE_INGREDIENTS_SYSTEM_PROMPT },
				{ role: "user", content: JSON.stringify(items) },
			],
		});
		const parsed = categorizeIngredientsResponseSchema.safeParse(
			extractJson(completion.choices[0]?.message?.content),
		);
		if (!parsed.success) {
			return {
				type: "error",
				message: "Malformed categorize-ingredients response from Groq",
			};
		}
		return { type: "success", items: parsed.data.items };
	} catch (error) {
		return {
			type: "error",
			message:
				error instanceof Error
					? error.message
					: "Ingredient categorization failed",
		};
	}
}
